### ISSUE TITLE
Assumption knobs to tune

### ISSUE THREAD

**Issue by kravets** [creamofthecoin/btcsecuritybudget#14]
It would be nice to play with assumption by having sliders. For example, I don't find the 1% of market cap as "high enough revenue for security" realistic, so I'd want to tune that down to say 0.2%

Same applies to avg cost of a tx being assumed at $100 being highest acceptable to plebs, etc.

Cheers and great site thx for your efforts

**Comment by KevinMusgrave** [comment]
Thanks for the suggestion. The latest version has a Settings button where you can change the thresholds.
